### ISSUE TITLE
temporary invulnerability (as when taking a bunny) disappears when changing rooms

### ISSUE THREAD

**Issue by dougmencken** [dougmencken/HeadOverHeels#60]
![yep it disappears](https://github.com/dougmencken/HeadOverHeels/assets/3457110/6f2dcf82-24dd-4273-8ce3-c1426b270ffe)

**Comment by dougmencken** [comment]
here

https://github.com/dougmencken/HeadOverHeels/blob/d89d8d8ea3d1029f1a2000f7d2e9600b7f0c6529/source/AvatarItem.cpp#L504

the remaining shield is determined by the value of AvatarItem’s timer, which is not copied within the copy constructor

https://github.com/dougmencken/HeadOverHeels/blob/d89d8d8ea3d1029f1a2000f7d2e9600b7f0c6529/source/AvatarItem.cpp#L26

**Comment by dougmencken** [comment]
and there

https://github.com/dougmencken/HeadOverHeels/blob/d89d8d8ea3d1029f1a2000f7d2e9600b7f0c6529/source/GameInfo.hpp#L171

it’s worth adding `+ 0.5` and thus not losing much on rounding down to a smaller integer

**Comment by dougmencken** [comment]
```
non-sequential decrement of shield points for character head : was 84 and now changes to 0
terminate called after throwing an instance of 'short'
(gdb) bt
#7  0x00007ffff7aa5a49 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7abb128 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00005555555ef44b in GameInfo::setShieldPointsByName (this=<optimized out>, character="head", points=points@entry=0) at GameInfo.cpp:122
#10 0x00005555555b314c in GameInfo::setShieldSecondsByName (seconds=4.6355719518956121e-310, character="head", this=<optimized out>)
    at /home/dougmencken/boo/source/GameInfo.hpp:96
#11 0x000055555562f66b in behaviors::PlayerControlled::update (this=0x555556debac0) at behaviors/PlayerControlled.cpp:46
#12 0x00005555555c176c in Mediator::update (this=0x55555709e300) at Mediator.cpp:121
#13 0x00005555555c1bd8 in Mediator::updateThread (mediatorAsVoid=0x55555709e300) at Mediator.cpp:171
#14 0x00007ffff769ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#15 0x00007ffff7729c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb) quit

```

**Comment by dougmencken** [comment]
currently, the Timer class has a flaw : [timevals are initialized to zeroes in the constructor](https://github.com/dougmencken/HeadOverHeels/blob/b70055d22c7726ab892b1031c7ef8981253c18f8/source/Timer.cpp#L6), and getValue() for any new(* instance of Timer returns the seconds elapsed since “the Unix time zero”— that’s midnight UTC on January 1st, 1970

*) such a “newness” lasts until the first go()

**Comment by dougmencken** [comment]
> `go()` or `reset()`

meanwhile, they do perfectly the same— why are there both?

**Comment by dougmencken** [comment]
looks like it’s worth moving the shield timer to **GameInfo**

**Comment by dougmencken** [comment]
Only the one gotcha remains unaddressed : when the game is paused, the shield decrease timer tick-tock-tick-tocks!
Since the last patch, the seconds of shield are updated in the Mediator update thread
https://github.com/dougmencken/HeadOverHeels/blob/c7fbeeda3d7f84a116f3661e10eaa842eafbf793/source/Mediator.cpp#L139
which isn’t invoked on pause.

Moving the invocation of ``updateShield()`` to a new dedicated thread that runs independently is something to think about

**Comment by dougmencken** [comment]
solved
