### ISSUE TITLE
The game gets stuck when the character eats the reincarnation fish

### ISSUE THREAD

**Issue by hendrikbez** [dougmencken/HeadOverHeels#77]
I have tried
![head](https://github.com/user-attachments/assets/cece3c2d-5cac-4345-9e44-586829d3501e)
 two time and every time I get the first fish for Head the game freeze.

removing avatar item "character head @ blacktooth7.xml" from room "blacktooth7.xml"
and removing the copy of character "head" created on entry to this room
there’re no characters left in room "blacktooth7.xml" thus bye that room
the exit coordinates from room "blacktooth7.xml" are x=25 y=159 z=0
the entry coordinates to room "blacktooth8fish.xml" are x=25 y=12 z=48
setting the way of entry = "east" for head.8Y6OqiI0XwU7
adding character "head" to room "blacktooth8fish.xml"
character "head" was copied to restart this room
character "head" is yet active in "blacktooth8fish.xml"

**Comment by dougmencken** [comment]
![Screenshot From 2024-10-29 14-51-32](https://github.com/user-attachments/assets/41b6c2d3-0a88-446b-bd03-880e267bddeb)

I confirm it hangs with the current master (b202272551015e26e84d001a200f82d11e31854d) on Ubuntu

**Comment by dougmencken** [comment]
I’ll just leave it here

```
[New Thread 0x7fffed0006c0 (LWP 65861)]
GameManager::eatFish ( character "head", room "blacktooth8fish.xml" )
[Switching to Thread 0x7fffed0006c0 (LWP 65861)]

Thread 17 "headoverheels" hit Breakpoint 1, Isomot::pauseMe (this=this@entry=0x5555556d0e10 <GameManager::instance+240>) at Isomot.cpp:96
96	{
(gdb) bt
#0  Isomot::pauseMe (this=this@entry=0x5555556d0e10 <GameManager::instance+240>) at Isomot.cpp:96
#1  0x00005555555f0d8c in GameManager::pause (this=this@entry=0x5555556d0d20 <GameManager::instance>) at GameManager.cpp:214
#2  0x00005555555f27a3 in GameManager::eatFish (this=0x5555556d0d20 <GameManager::instance>, character=..., room=0x5555596fb500) at GameManager.cpp:744
#3  0x00005555555c22e1 in AvatarItem::saveGame (this=<optimized out>) at AvatarItem.cpp:530
#4  0x000055555563136f in behaviors::Bonus::takeIt (this=this@entry=0x555559d68d20, whoTakes=...) at behaviors/Bonus.cpp:221
#5  0x0000555555631ca4 in behaviors::Bonus::update (this=0x555559d68d20) at behaviors/Bonus.cpp:146
#6  0x00005555555d1cb2 in Mediator::update (this=0x555559601e70) at Mediator.cpp:127
#7  0x00005555555d2188 in Mediator::updateFromThread (mediatorAsVoid=0x555559601e70) at Mediator.cpp:183
#8  0x00007ffff76a1e2e in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#9  0x00007ffff7733a4c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb) c
Continuing.
[Switching to Thread 0x7ffff78d6b80 (LWP 65615)]

Thread 1 "headoverheels" hit Breakpoint 1, Isomot::pauseMe (this=this@entry=0x5555556d0e10 <GameManager::instance+240>) at Isomot.cpp:96
96	{
(gdb) bt
#0  Isomot::pauseMe (this=this@entry=0x5555556d0e10 <GameManager::instance+240>) at Isomot.cpp:96
#1  0x00005555555f0d8c in GameManager::pause (this=0x5555556d0d20 <GameManager::instance>) at GameManager.cpp:214
#2  0x0000555555652605 in gui::Action::doIt (this=0x555559294110) at guiactions/Action.hpp:34
#3  gui::Label::handleKey (this=<optimized out>, key=...) at gui/Label.cpp:50
#4  0x0000555555650bd6 in gui::GuiManager::loop (this=this@entry=0x555555710d60) at gui/GuiManager.cpp:99
#5  0x0000555555650c70 in gui::GuiManager::firstMenu (this=0x555555710d60) at gui/GuiManager.cpp:84
#6  0x0000555555580419 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:205
(gdb)
```

**Comment by dougmencken** [comment]
the savegame file for easy testing

```
<savegame version="2.4">
    <exploredRooms>
        <visited room="blacktooth1head.xml"/>
        <visited room="blacktooth2.xml"/>
        <visited room="blacktooth23heels.xml"/>
        <visited room="blacktooth24.xml"/>
        <visited room="blacktooth25.xml"/>
        <visited room="blacktooth26.xml"/>
        <visited room="blacktooth27fish.xml"/>
        <visited room="blacktooth28.xml"/>
        <visited room="blacktooth3.xml"/>
        <visited room="blacktooth4.xml"/>
        <visited room="blacktooth5.xml"/>
        <visited room="blacktooth6.xml"/>
        <visited room="blacktooth7.xml"/>
        <visited room="blacktooth8fish.xml"/>
        <visited room="blacktooth9.xml"/>
    </exploredRooms>
    <takenBonuses>
        <bonus of="donuts" in="blacktooth6.xml"/>
        <bonus of="horn" in="blacktooth9.xml"/>
        <bonus of="handbag" in="blacktooth28.xml"/>
    </takenBonuses>
    <starring>
        <character name="head">
            <active>true</active>
            <room>blacktooth9.xml</room>
            <x>16</x>
            <y>69</y>
            <z>24</z>
            <lives>8</lives>
            <heading>north</heading>
            <hasHorn>yes</hasHorn>
            <donuts>6</donuts>
        </character>
        <character name="heels">
            <room>blacktooth28.xml</room>
            <x>16</x>
            <y>69</y>
            <z>24</z>
            <lives>8</lives>
            <heading>north</heading>
            <hasHandbag>yes</hasHandbag>
        </character>
    </starring>
</savegame>
```

**Comment by dougmencken** [comment]
neither of the last two commits, 87ab87bc8377b6fe7af982084f9813a45695588c and 500906abed5629cee8ebea5773ee059ea6e6e4a2, solves this problem

**Comment by dougmencken** [comment]
here in the game I jump for the reincarnation fish
```
GameManager::eatFish ( character "head", room "blacktooth8fish.xml" )
GameManager::pause ()
Isomot::pauseMe ()
GameManager::pause ()
[Thread 0x7fffee0006c0 (LWP 22717) exited]
doing action gui::ContinueGame
[New Thread 0x7fffe2a006c0 (LWP 22845)]
GameManager::resume ()
done action gui::ContinueGame
Isomot::resumeMe ()
[New Thread 0x7fffee0006c0 (LWP 22846)]
[Thread 0x7fffee0006c0 (LWP 22846) exited]
```

it hangs, thus I type [control]+[c]

```
^C
Thread 1 "headoverheels" received signal SIGINT, Interrupt.
0x00007ffff76f38e3 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffffffdb40, rem=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
(gdb) bt
#0  0x00007ffff76f38e3 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffffffdb40, rem=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
#1  0x00007ffff7701597 in __GI___nanosleep (req=<optimized out>, rem=<optimized out>) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x0000555555582984 in somn::nanoSleep (nanoseconds=25000000) at sleep.cpp:26
#3  somn::milliSleep (milliseconds=milliseconds@entry=25) at sleep.cpp:11
#4  0x000055555564fef2 in gui::GuiManager::loop (this=this@entry=0x555555710280) at gui/GuiManager.cpp:108
#5  0x000055555564ffd7 in gui::GuiManager::firstMenu (this=0x555555710280) at gui/GuiManager.cpp:85
#6  0x0000555555580611 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:205
```

seeing this is not a hung thread, I look at the list of all threads

```
(gdb) info thread 
  Id   Target Id                                         Frame 
* 1    Thread 0x7ffff78d6b80 (LWP 22629) "headoverheels" 0x00007ffff76f38e3 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffffffdb40, rem=0x0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
  2    Thread 0x7ffff72006c0 (LWP 22632) "headoverheels" 0x00007ffff7730a57 in __GI___select (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x7ffff71ffdf0)
    at ../sysdeps/unix/sysv/linux/select.c:69
  3    Thread 0x7ffff68006c0 (LWP 22683) "headoverheels" 0x00007ffff7730a57 in __GI___select (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x7ffff67ffde0)
    at ../sysdeps/unix/sysv/linux/select.c:69
  6    Thread 0x7ffff58006c0 (LWP 22690) "module-rt"     0x00007ffff7733e72 in epoll_wait (epfd=11, events=0x7ffff57ffa90, maxevents=32, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  7    Thread 0x7ffff4e006c0 (LWP 22691) "alsa-pipewire" 0x00007ffff7733e72 in epoll_wait (epfd=4, events=0x7ffff4dffa90, maxevents=32, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  8    Thread 0x7fffefe006c0 (LWP 22693) "module-rt"     0x00007ffff7733e72 in epoll_wait (epfd=25, events=0x7fffefdffa90, maxevents=32, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  9    Thread 0x7fffef4006c0 (LWP 22694) "alsa-pipewire" 0x00007ffff7733e72 in epoll_wait (epfd=17, events=0x7fffef3ffa90, maxevents=32, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  10   Thread 0x7fffeea006c0 (LWP 22696) "data-loop.0"   0x00007ffff7733e72 in epoll_wait (epfd=7, events=0x7fffee9ffa00, maxevents=32, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  15   Thread 0x7fffe3e006c0 (LWP 22718) "headoverheels" 0x00007ffff76f38e3 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffe3dffe80, rem=0x0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
  21   Thread 0x7fffe34006c0 (LWP 22750) "headoverheels" 0x00007ffff76f38e3 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffe33ffe80, rem=0x0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
  55   Thread 0x7fffed0006c0 (LWP 22842) "headoverheels" futex_wait (futex_word=0x55555b0e7798, expected=2, private=0) at ../sysdeps/nptl/futex-internal.h:146
  56   Thread 0x7fffe2a006c0 (LWP 22845) "headoverheels" futex_wait (futex_word=0x55555b0e7770, expected=2, private=0) at ../sysdeps/nptl/futex-internal.h:146
```

the last two seem quite relevant

```
(gdb) thread 55
[Switching to thread 55 (Thread 0x7fffed0006c0 (LWP 22842))]
#0  futex_wait (futex_word=0x55555b0e7798, expected=2, private=0) at ../sysdeps/nptl/futex-internal.h:146
146	in ../sysdeps/nptl/futex-internal.h
(gdb) bt
#0  futex_wait (futex_word=0x55555b0e7798, expected=2, private=0) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x55555b0e7798, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007ffff76a5541 in lll_mutex_lock_optimized (mutex=0x55555b0e7798) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x55555b0e7798) at ./nptl/pthread_mutex_lock.c:93
#4  0x00005555555d9db0 in Mediator::lockFreeItemsMutex (this=<optimized out>) at /home/dougmencken/boo/source/Mediator.hpp:194
#5  Room::draw (this=0x55555ac82810) at Room.cpp:1300
#6  0x00005555555d8ea3 in Drawable::drawOn (this=0x55555ac82810, where=...) at /home/dougmencken/boo/source/Drawable.hpp:32
#7  Drawable::drawOn (this=0x55555ac82810, where=...) at /home/dougmencken/boo/source/Drawable.hpp:25
#8  Room::drawRoom (this=0x55555ac82810) at Room.cpp:1263
#9  0x00005555556110a8 in Isomot::updateMe (this=this@entry=0x5555556d0e30 <GameManager::instance+240>) at Isomot.cpp:197
#10 0x00005555555eff0f in GameManager::pause (this=this@entry=0x5555556d0d40 <GameManager::instance>) at GameManager.cpp:239
#11 0x00005555555f1793 in GameManager::eatFish (this=0x5555556d0d40 <GameManager::instance>, character=..., room=0x55555ac82810) at GameManager.cpp:767
#12 0x00005555555c16cb in AvatarItem::saveGame (this=<optimized out>) at AvatarItem.cpp:530
#13 0x000055555563060f in behaviors::Bonus::takeIt (this=this@entry=0x55555b095520, whoTakes=...) at behaviors/Bonus.cpp:221
#14 0x0000555555630f44 in behaviors::Bonus::update (this=0x55555b095520) at behaviors/Bonus.cpp:146
#15 0x00005555555d1052 in Mediator::update (this=0x55555b0e7750) at Mediator.cpp:127
#16 0x00005555555d1528 in Mediator::updateFromThread (mediatorAsVoid=0x55555b0e7750) at Mediator.cpp:183
#17 0x00007ffff76a1e2e in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#18 0x00007ffff7733a4c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

```
(gdb) thread 56
[Switching to thread 56 (Thread 0x7fffe2a006c0 (LWP 22845))]
#0  futex_wait (futex_word=0x55555b0e7770, expected=2, private=0) at ../sysdeps/nptl/futex-internal.h:146
146	in ../sysdeps/nptl/futex-internal.h
(gdb) bt
#0  futex_wait (futex_word=0x55555b0e7770, expected=2, private=0) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x55555b0e7770, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007ffff76a5541 in lll_mutex_lock_optimized (mutex=0x55555b0e7770) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x55555b0e7770) at ./nptl/pthread_mutex_lock.c:93
#4  0x00005555555d9da3 in Mediator::lockGridItemsMutex (this=<optimized out>) at /home/dougmencken/boo/source/Mediator.hpp:191
#5  Room::draw (this=0x55555ac82810) at Room.cpp:1299
#6  0x00005555555d8ea3 in Drawable::drawOn (this=0x55555ac82810, where=...) at /home/dougmencken/boo/source/Drawable.hpp:32
#7  Drawable::drawOn (this=0x55555ac82810, where=...) at /home/dougmencken/boo/source/Drawable.hpp:25
#8  Room::drawRoom (this=0x55555ac82810) at Room.cpp:1263
#9  0x00005555556110a8 in Isomot::updateMe (this=this@entry=0x5555556d0e30 <GameManager::instance+240>) at Isomot.cpp:197
#10 0x00005555555f978d in GameManager::update (this=0x5555556d0d40 <GameManager::instance>) at GameManager.cpp:175
#11 0x00005555555f9c9a in GameManager::resume (this=<optimized out>) at GameManager.cpp:375
#12 0x00005555555f9cea in GameManager::beginOrResume (pointerToBoolean=<optimized out>) at /home/dougmencken/boo/source/GameManager.hpp:49
#13 0x00007ffff76a1e2e in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#14 0x00007ffff7733a4c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb) 
```

**Comment by dougmencken** [comment]
the problem was in fact that eating the fish by the character tried to pause the isometric engine from the items update thread, and thus a mutex race occurred
